### ISSUE TITLE
Synchronization Exploration

### ISSUE THREAD

**Issue by quasiben** [rapidsai/rmm#332]
In exploring synchronization issues in RMM I found some peculiar behavior.   I was testing out working stealing with Dask and I was getting an older error we previously saw with dask-cuda:

```
distributed.worker - WARNING -  Compute Failed
Function:  fastadd
args:      (44, 0    1
1    2
2    3
3    4
dtype: int64)
kwargs:    {}
Exception: RuntimeError('CUDA_ERROR_INVALID_CONTEXT')
```
`CUDA_ERROR_INVALID_CONTEXT` error used to happen when we didn't manage the cuda context well when forking or spawning new threads.  This is now happening with the recent [Synchronize stream in DeviceBuffer PR: 326]( https://github.com/rapidsai/rmm/pull/326 ). If you revert this change, there is no longer a `CUDA_ERROR_INVALID_CONTEXT` error.

MRE:

```python
from dask_cuda import LocalCUDACluster
from dask_cuda.initialize import initialize
import rmm
from dask.utils import parse_bytes
from distributed import Client, wait
from time import sleep
import cudf
import cupy


def setup_rmm_pool(client):
    client.run(
        cudf.set_allocator,
        pool=True,
        initial_pool_size= parse_bytes("3GB"),
        allocator="default"
    )
    client.run(
        cupy.cuda.set_allocator,
        rmm.rmm_cupy_allocator
    )


def slowadd(x, y, delay=0.02):
    sleep(delay)
    import threading
    print(threading.get_ident())
    return x + y

if __name__ == "__main__":
    enable_nvlink = False
    enable_infiniband = False
    enable_tcp_over_ucx = False
    initialize(create_cuda_context=True)
    cluster = LocalCUDACluster(local_directory="/tmp/bzaitlen",
                              rmm_pool_size=parse_bytes('3GB'),
                              protocol='tcp',
                              interface='enp1s0f0')
    client = Client("tcp://10.33.227.163:8786")
    setup_rmm_pool(client)

    cdf = cudf.Series([1,2,3,4])
    [x] = client.scatter([cdf], workers=['0'])
    futures = client.map(slowadd, range(50), [x] * 50)
    wait(futures)
    worker_data = client.run(lambda dask_worker: dask_worker.data)
    for k, device_host_file in worker_data.items():
        assert len(device_host_file.host) > 2
```

**Comment by jakirkham** [comment]
(the link was coming back to this issue for some reason. Edited to include the full PR URL to fix it 🙂)

**Comment by jakirkham** [comment]
> `client = Client("tcp://10.33.227.163:8786")`

Do we need to specify the address in `Client` for the reproducer or can that be dropped?

**Comment by jakirkham** [comment]
Also it appears we are passing `rmm_pool_size` to `LocalCUDACluster`, which sets up RMM pools on the workers. However we are then explicitly doing this with the `setup_rmm_pool` function after. Do we need both or could just one of these be used?

**Comment by quasiben** [comment]
With a new env I am no longer able to reproduce the issue:

> conda create -n 20200319 -c rapidsai-nightly -c conda-forge -c nvidia cudf=0.13 dask-cudf dask-cuda ipython ucx-py ipdb cudatoolkit=10.2 pytest-asyncio jupyter cython ipdb  automake make libtool pkg-config libhwloc python=3.7

I am going to check a few more things.  If I can't reproduce I will close

**Comment by jakirkham** [comment]
FWIW I have a slightly updated script that looks like this. Feel free to point out anything I may have missed 🙂

<details>
<summary>Script:</summary>

```python
#!/usr/bin/env python


import threading
from time import sleep

import cudf
from dask_cuda import LocalCUDACluster
from dask_cuda.initialize import initialize
from distributed import Client, wait


def slowadd(x, y, delay=0.02):
    sleep(delay)
    print(threading.get_ident())
    return x + y


if __name__ == "__main__":
    enable_nvlink = False
    enable_infiniband = False
    enable_tcp_over_ucx = False
    initialize(create_cuda_context=True)
    cluster = LocalCUDACluster(rmm_pool_size="3GB", protocol="tcp")
    client = Client(cluster)

    cdf = cudf.Series([1, 2, 3, 4])
    [x] = client.scatter([cdf], workers=["0"])
    futures = client.map(slowadd, range(50), [x] * 50)
    wait(futures)
    worker_data = client.run(lambda dask_worker: dask_worker.data)
    for k, device_host_file in worker_data.items():
        assert len(device_host_file.host) > 2
```

</details>

When I run this, I get the following error...

<details>
<summary>Traceback:</summary>

```python
distributed.core - ERROR - missing port number in address '0'
Traceback (most recent call last):
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 2758, in scatter
    workers = [self.coerce_address(w) for w in workers]
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 2758, in <listcomp>
    workers = [self.coerce_address(w) for w in workers]
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 4848, in coerce_address
    addr = resolve_address(addr)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 174, in resolve_address
    return unparse_address(scheme, backend.resolve_address(loc))
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/tcp.py", line 529, in resolve_address
    host, port = parse_host_port(loc)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 90, in parse_host_port
    port = _default()
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 69, in _default
    raise ValueError("missing port number in address %r" % (address,))
ValueError: missing port number in address '0'
Traceback (most recent call last):
  File "./rmm_gh_332.py", line 28, in <module>
    [x] = client.scatter([cdf], workers=["0"])
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/client.py", line 2099, in scatter
    hash=hash,
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/client.py", line 1986, in _scatter
    timeout=timeout,
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/core.py", line 757, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/core.py", line 556, in send_recv
    raise exc.with_traceback(tb)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 2758, in scatter
    workers = [self.coerce_address(w) for w in workers]
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 2758, in <listcomp>
    workers = [self.coerce_address(w) for w in workers]
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/scheduler.py", line 4848, in coerce_address
    addr = resolve_address(addr)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 174, in resolve_address
    return unparse_address(scheme, backend.resolve_address(loc))
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/tcp.py", line 529, in resolve_address
    host, port = parse_host_port(loc)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 90, in parse_host_port
    port = _default()
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.6/site-packages/distributed/comm/addressing.py", line 69, in _default
    raise ValueError("missing port number in address %r" % (address,))
ValueError: missing port number in address '0'
```

</details>

**Comment by quasiben** [comment]
I am going to close -- I can't reproduce anymore.  It's very likely my env was messed up from various builds
