### ISSUE TITLE
[BUG] crash from pool_memory_resource

### ISSUE THREAD

**Issue by rongou** [rapidsai/rmm#453]
**Describe the bug**
While running one of the Spark benchmarks with PTDS enabled, got this crash that seems to be from RMM:
```bash
20/07/30 00:43:55 WARN TaskSetManager: Lost task 200.0 in stage 23.0 (TID 1135, 10.150.30.3, executor 11): ai.rapids.cudf.CudfException: CUDA error at: 
/home/rou/miniconda3/envs/cudf_dev/include/rmm/mr/device/pool_memory_resource.hpp182: cudaErrorIllegalAddress an illegal memory access was encountered
	at ai.rapids.cudf.ColumnVector.castTo(Native Method)
	at ai.rapids.cudf.ColumnVector.castTo(ColumnVector.java:1420)
	at com.nvidia.spark.rapids.GpuCast.doColumnar(GpuCast.scala:451)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:125)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$processIncomingBatch$1(aggregate.scala:514)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:160)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:157)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:157)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:192)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.processIncomingBatch(aggregate.scala:513)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

20/07/30 00:43:55 WARN TaskSetManager: Lost task 236.0 in stage 23.0 (TID 1171, 10.150.30.3, executor 11): ai.rapids.cudf.CudaException: an illegal memory access was encountered
	at ai.rapids.cudf.Cuda.memcpy(Native Method)
	at ai.rapids.cudf.Cuda.memcpy(Cuda.java:272)
	at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:43)
	at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:113)
	at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1481)
	at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1522)
	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.tryReadNext(GpuColumnarBatchSerializer.scala:152)
	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.hasNext(GpuColumnarBatchSerializer.scala:175)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.RemoveEmptyBatchIterator.hasNext(GpuCoalesceBatches.scala:124)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:264)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:147)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:137)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:338)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps/Code to reproduce bug**
Not sure how to reproduce this in isolation. I was running one of the spark-rapids integration tests that's like TPCx-BB query 5.

**Expected behavior**
Should not crash.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RMM install: conda

**Additional context**
Maybe @revans2 has some ideas.

**Comment by harrism** [comment]
I don't know how to triage this. Certainly need at least a C++ call stack. cuDF debug builds don't work but RMM debug builds do, so you could use a debug RMM if the crash is indeed happening there.

**Comment by rongou** [comment]
Isn't RMM header-only now if we don't use CNMeM? How would we do a debug build?

The first line of the log does point to this line: https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/mr/device/pool_memory_resource.hpp#L182

**Comment by harrism** [comment]
Good point. I didn't see that line number because it requires scrolling right. I edited the issue description to put the RMM error on its own line.

That error does not come from that line. It must be from a CUDA kernel previous to that line. That error leaves the CUDA context in a bad state so that all subsequent calls will return the same error. Not saying that the illegal address is not coming from an RMM allocation, just that we can't debug it at that line.

Need to run in cuda-gdb or cuda-memcheck to try to catch the error where it first occurred.

**Comment by harrism** [comment]
@rongou you could also try running with #449.

**Comment by harrism** [comment]
@rongou any repro with latest?

**Comment by rongou** [comment]
Yeah this was probably a one-off thing. Closing it for now.
